version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 99
    rebase-strategy: "disabled"
    ignore:
      # requires Ruby >= 2.4.0
      - dependency-name: annotate
        versions:
        - ">= 3.1.1"
      - dependency-name: capybara
        versions:
        - ">= 3.16.0"
      - dependency-name: fast_gettext
        versions:
        - ">= 2.0.3"
      - dependency-name: icalendar
        versions:
        - ">= 2.6.0"
      - dependency-name: launchy
        versions:
        - ">= 2.5.0"
      - dependency-name: maxmind-db
        versions:
        - ">= 1.1.0"
      - dependency-name: pry-byebug
        versions:
        - ">= 2.8.0"
      - dependency-name: rubocop
        versions:
        - ">= 0.82.0"
      - dependency-name: rubocop-performance
        versions:
        - ">= 1.6.0"
      - dependency-name: sass-rails
        versions:
        - ">= 5.0.8"

      # pry-byebug requires Ruby >= 2.4.0
      - dependency-name: pry
        versions:
        - ">= 0.13.0"

      # requires Ruby >= 2.4
      - dependency-name: rubyzip
        versions:
        - ">= 2.0.0"

      # requires Ruby ~> 2.4
      - dependency-name: holidays
        versions:
        - ">= 8.0.0"

      # requires Ruby >= 2.4.6
      - dependency-name: globalize
        versions:
        - ">= 5.3.0"

      # requires Ruby >= 2.5.0
      - dependency-name: capybara
        versions:
        - ">= 3.33.0"
      - dependency-name: gettext
        versions:
        - ">= 3.3.0"

      # factory_bot requires Ruby >= 2.5.0
      - dependency-name: factory_bot_rails
        versions:
        - ">= 6.0.0"

      # sprockets requires Ruby >= 2.5.0
      - dependency-name: sass-rails
        versions:
        - ">= 6.0.0"

      # capistrano 3 is a major API change that we're unlikely to support
      - dependency-name: capistrano
        versions:
        - ">= 3.0.0"
