#!/bin/bash
TOP_DIR="$(dirname "$BASH_SOURCE")/.."
cd "$TOP_DIR"
if [ "$1" == "--loop" ]
then
  ${RUBY_WRAPPER}bundle exec rails runner 'TrackMailer.alert_tracks_loop'
else
  ${RUBY_WRAPPER}bundle exec rails runner 'TrackMailer.alert_tracks'
fi
