#!/bin/bash
TOP_DIR="$(dirname "$BASH_SOURCE")/.."
cd "$TOP_DIR"
if [ "$1" == "--loop" ]
then
  /home/alaveteli/.rvm/gems/ruby-2.0.0-p353/wrappers/bundle exec rails runner 'TrackMailer.alert_tracks_loop'
else
  /home/alaveteli/.rvm/gems/ruby-2.0.0-p353/wrappers/bundle exec rails runner 'TrackMailer.alert_tracks'
fi
