#!/bin/bash
#
# annotates the models in app/ with schema information

/home/alaveteli/.rvm/gems/ruby-2.0.0-p353/wrappers/bundle exec annotate --show-migration --position before --exclude tests,fixtures
