#!/bin/bash
TOP_DIR="$(dirname "$BASH_SOURCE")/.."
cd "$TOP_DIR"
/home/alaveteli/.rvm/gems/ruby-2.0.0-p353/wrappers/bundle exec rails runner 'PostRedirect.delete_old_post_redirects'
/home/alaveteli/.rvm/gems/ruby-2.0.0-p353/wrappers/bundle exec rails runner 'TrackThingsSentEmail.delete_old_track_things_sent_email'
